/** File Hash: 9d4695dd4c71fde6a12f31081d3d85e53df69bbc332a4388336bad9438f960c2 */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */

import type { SeatingPlanPlace } from "@/dtos/seatingplan/seating-plan-place"

export interface SeatingPlanSector {
  id?: number;
  x: number;
  y: number;
  width: number;
  height: number;
  name: string;
  pricePercent: number;
  isAvailable: boolean;
  places: SeatingPlanPlace[];
}
