/** File Hash: f366af8bac634e4616bb7d7646acde3d52ef7d82ede0a109c91f323acf84e3e7 */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */

import type { SeatingPlanSector } from "@/dtos/seatingplan/seating-plan-sector"

export interface SeatingPlan {
  id: number;
  name: string;
  sectors: SeatingPlanSector[];
}
