/** File Hash: a4eaf3e9f603eb81f2c03826b4b0571880e1fce25d82b4748eda998f17729b0c */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */


export interface SeatingPlanSearch {
  name?: string;
}
