/** File Hash: a4fa7b8d814448d46583ba5967ee89306fe37f0e5a748cd80595abe4b37320d3 */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */

import type { PlaceType } from "@/dtos/place-type"

export interface SeatingPlanPlace {
  id: number;
  seatNumber: number;
  x: number;
  y: number;
  width: number;
  height: number;
  rowName: string;
  placeType: PlaceType;
}
