/** File Hash: 204bd07b87d085aa84a51884e04212d3016a764dc383a20a77fb33d334df2137 */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */


export interface StandingCapacityDetail {
  seatingPlanPlaceId: number;
  occupied: number;
  capacity: number;
}
