/** File Hash: ef36b15e0519e65ae6ee312354200dc8338f4c83e7ffe1bf85e1a4d7eb87cd74 */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */


export interface StandingCapacitySearch {
  eventShowId: number;
  seatingPlanId: number;
}
