/** File Hash: 38ace971d664b91dd3d5e12fb23aeb1490b54da45833090037f6e6e0d20c3841 */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */


export interface LocationDetail {
  id: number;
  name: string;
  country: string;
  city: string;
  postalCode: string;
  address: string;
}
