/** File Hash: 9364f6af06e4eb948a0fedd7c171c2117c4c4c785dd5f3263669c2ae8e174cbc */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */


export interface LocationSearch {
  name?: string;
  country?: string;
  city?: string;
  postalCode?: string;
  address?: string;
}
