/** File Hash: 4ae90082685c55ccc28332a70c1755f64ca1aeb9f3ca1c081d777ce26abebcf5 */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */

import type { IsoDateTimeString } from "@/dtos/iso-date-time-string"
import type { EventType } from "@/dtos/event-type"

export interface NewsSearch {
  content?: string;
  from?: IsoDateTimeString;
  to?: IsoDateTimeString;
  eventTitle?: string;
  eventType?: EventType;
  read?: boolean | null;
}
