/** File Hash: d1446ef4de6fe307bcc019ff1a80aef810a9745f7c5dac75ff1d193e9641f61f */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */


export interface NewsCreate {
  title: string;
  summary: string;
  text: string;
  eventId: number;
  imageId: number;
}
