/** File Hash: c0158e54ae4cc67df786d8cbc6768368c84a8b55f6d8730cb93c0df2d8b7ab8e */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */

import type { IsoDateTimeString } from "@/dtos/iso-date-time-string"
import type { EventDetail } from "@/dtos/event/event-detail"

export interface NewsDetail {
  id: number;
  title: string;
  summary: string;
  text: string;
  published: IsoDateTimeString;
  event: EventDetail;
  imageName: string;
}
