/** File Hash: 06937232525da1a710c76a86bd580eb7b54a2a626bdbc0e957814a348772de9e */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */

import { useService } from './service';
import type { ArtistSearch } from "@/dtos/artist/artist-search"
import type { Page } from "@/dtos/page"
import type { Pagination } from "@/dtos/pagination"
import type { ArtistDetail } from "@/dtos/artist/artist-detail"

export function useArtistService() {
  const basePath = `api/v1/artists`;
  const { api, filterSearchParams } = useService(basePath);
  
  async function findByFilters(artistSearchDto: ArtistSearch, page: Page): Promise<Pagination<ArtistDetail>> {
    return api.get(``, { searchParams: filterSearchParams([['pageSize', page.pageSize], ['lastName', artistSearchDto.lastName], ['stageName', artistSearchDto.stageName], ['firstName', artistSearchDto.firstName], ['pageIndex', page.pageIndex]]) }).json();
  }
  async function findById(id: number): Promise<ArtistDetail> {
    return api.get(`${id}`).json();
  }
  return {
    findByFilters,
    findById,
  };
}
