/** File Hash: aa39c866ebf064ef4c0af65731da8f581ff68273450085650dfe247c6bf4e891 */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */

import { useService } from './service';
import type { EventShowCreate } from "@/dtos/eventshow/event-show-create"
import type { EventShowDetail } from "@/dtos/eventshow/event-show-detail"
import type { Page } from "@/dtos/page"
import type { Pagination } from "@/dtos/pagination"
import type { EventShowSearch } from "@/dtos/eventshow/event-show-search"

export function useEventShowService() {
  const basePath = `api/v1/eventshows`;
  const { api, filterSearchParams } = useService(basePath);
  
  async function createShow(createDto: EventShowCreate): Promise<EventShowDetail> {
    return api.post(``, { json: createDto }).json();
  }
  async function findByEventId(eventId: number, pageDto: Page): Promise<Pagination<EventShowDetail>> {
    return api.get(``, { searchParams: filterSearchParams([['pageSize', pageDto.pageSize], ['eventId', eventId], ['pageIndex', pageDto.pageIndex]]) }).json();
  }
  async function findByFilters(search: EventShowSearch, page: Page): Promise<Pagination<EventShowDetail>> {
    return api.get(``, { searchParams: filterSearchParams([['pageSize', page.pageSize], ['eventName', search.eventName], ['endDate', search.endDate], ['city', search.city], ['artistName', search.artistName], ['pageIndex', page.pageIndex], ['startDate', search.startDate], ['maxPrice', search.maxPrice], ['country', search.country], ['duration', search.duration], ['locationName', search.locationName], ['name', search.name], ['minPrice', search.minPrice]]) }).json();
  }
  async function findById(id: number): Promise<EventShowDetail> {
    return api.get(`${id}`).json();
  }
  async function findByLocationId(locationId: number, pageDto: Page): Promise<Pagination<EventShowDetail>> {
    return api.get(``, { searchParams: filterSearchParams([['pageSize', pageDto.pageSize], ['locationId', locationId], ['pageIndex', pageDto.pageIndex]]) }).json();
  }
  return {
    createShow,
    findByEventId,
    findByFilters,
    findById,
    findByLocationId,
  };
}
