/** File Hash: 109a457b0e6864f8ae21e7d5f72c0e7e88c7e52965d5af7989b3a9af318f3375 */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */

import { useService } from './service';
import type { ImageMedia } from "@/dtos/image-media"

export function useImageMediaService() {
  const basePath = `api/v1/images`;
  const { api, filterSearchParams } = useService(basePath);
  
  async function create(file: any): Promise<ImageMedia> {
    return api.post(``, { searchParams: filterSearchParams([['file', file]]) }).json();
  }
  async function find(name: string): Promise<any> {
    return api.get(`${name}`).json();
  }
  async function findDetails(name: string): Promise<ImageMedia> {
    return api.get(`${name}/info`).json();
  }
  async function remove(name: string): Promise<void> {
    await api.delete(`${name}`)
  }
  return {
    create,
    find,
    findDetails,
    remove,
  };
}
