/** File Hash: 553c35d77e6f2829c92b6a6ad3062480c358bc2ff4bf03e6719fa84c6f23a292 */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */

import { useService } from './service';
import type { Page } from "@/dtos/page"
import type { Pagination } from "@/dtos/pagination"
import type { InvoiceDetail } from "@/dtos/invoice/invoice-detail"

export function useInvoiceService() {
  const basePath = `api/v1/invoices`;
  const { api, filterSearchParams } = useService(basePath);
  
  async function getAllByUser(page: Page): Promise<Pagination<InvoiceDetail>> {
    return api.get(``, { searchParams: filterSearchParams([['pageSize', page.pageSize], ['pageIndex', page.pageIndex]]) }).json();
  }
  async function getById(id: number): Promise<InvoiceDetail> {
    return api.get(`${id}`).json();
  }
  return {
    getAllByUser,
    getById,
  };
}
