/** File Hash: 8692a098ce60e5f304fcee8842da3d96f4937bceb2e708ce227c913af1552fee */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */

import { useService } from './service';
import type { MerchandisePurchase } from "@/dtos/merchandise/merchandise-purchase"
import type { MerchandisePurchaseDetail } from "@/dtos/merchandise/merchandise-purchase-detail"
import type { MerchandisePurchaseChangeQuantity } from "@/dtos/merchandise/merchandise-purchase-change-quantity"

export function useMerchandisePurchaseService() {
  const basePath = `api/v1/merchandise/purchases`;
  const { api, filterSearchParams } = useService(basePath);
  
  async function addMerchandiseProductToCart(merchandise: MerchandisePurchase): Promise<MerchandisePurchaseDetail> {
    return api.post(``, { json: merchandise }).json();
  }
  async function changeMerchandisePurchaseQuantity(id: number, quantityDto: MerchandisePurchaseChangeQuantity): Promise<MerchandisePurchaseDetail> {
    return api.patch(`${id}/quantity`, { json: quantityDto }).json();
  }
  async function removeMerchandisePurchaseFromCart(id: number): Promise<void> {
    await api.delete(`${id}`)
  }
  return {
    addMerchandiseProductToCart,
    changeMerchandisePurchaseQuantity,
    removeMerchandisePurchaseFromCart,
  };
}
