/** File Hash: 941ccc6edac957eb63090d445a92dde58c2c6afda99edbf7c87392ea4631f1bf */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */

import { useService } from './service';
import type { PasswordResetChange } from "@/dtos/passwordreset/password-reset-change"
import type { PasswordResetDetail } from "@/dtos/passwordreset/password-reset-detail"
import type { PasswordResetCreate } from "@/dtos/passwordreset/password-reset-create"

export function usePasswordResetService() {
  const basePath = `api/v1/password-resets`;
  const { api, filterSearchParams } = useService(basePath);
  
  async function changePasswordOfUser(passwordResetChangeDto: PasswordResetChange): Promise<void> {
    await api.put(``, { json: passwordResetChangeDto })
  }
  async function checkPasswordResetByUUID(token: string): Promise<PasswordResetDetail> {
    return api.get(`${token}`).json();
  }
  async function createPasswordReset(passwordResetCreateDto: PasswordResetCreate): Promise<void> {
    await api.post(``, { json: passwordResetCreateDto })
  }
  return {
    changePasswordOfUser,
    checkPasswordResetByUUID,
    createPasswordReset,
  };
}
