/** File Hash: aab09ca96dbd56dc413992fe7aed2168252cfe74197c0a4142d8d00ac5dc8cce */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */

import { useService } from './service';
import type { SeatingPlan } from "@/dtos/seatingplan/seating-plan"
import type { SeatingPlanSearch } from "@/dtos/seatingplan/seating-plan-search"
import type { Page } from "@/dtos/page"
import type { Pagination } from "@/dtos/pagination"
import type { StandingCapacitySearch } from "@/dtos/seatingplan/standing-capacity-search"
import type { StandingCapacityDetail } from "@/dtos/seatingplan/standing-capacity-detail"

export function useSeatingPlanService() {
  const basePath = `api/v1/seatingplans`;
  const { api, filterSearchParams } = useService(basePath);
  
  async function findByEventShow(id: number): Promise<SeatingPlan> {
    return api.get(`event-show/${id}`).json();
  }
  async function findByFilters(seatingPlanSearchDto: SeatingPlanSearch, pageDto: Page): Promise<Pagination<SeatingPlan>> {
    return api.get(``, { searchParams: filterSearchParams([['pageSize', pageDto.pageSize], ['name', seatingPlanSearchDto.name], ['pageIndex', pageDto.pageIndex]]) }).json();
  }
  async function getStandingPlaceCapacity(standingCapacitySearchDto: StandingCapacitySearch): Promise<StandingCapacityDetail[]> {
    return api.get(`capacity`, { searchParams: filterSearchParams([['seatingPlanId', standingCapacitySearchDto.seatingPlanId], ['eventShowId', standingCapacitySearchDto.eventShowId]]) }).json();
  }
  return {
    findByEventShow,
    findByFilters,
    getStandingPlaceCapacity,
  };
}
