/** File Hash: c836140e4df0d4dca995d0c4f1d624094de7bfdd736acbfa332252c4ea5174ad */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */

import type { MerchandiseSortOption } from "@/dtos/merchandise-sort-option"

export interface MerchandiseProductSearch {
  name: string;
  priceLowerBound: number;
  priceUpperBound: number;
  pointsLowerBound: number;
  pointsUpperBound: number;
  sortOption: MerchandiseSortOption;
}
