/** File Hash: 91d115e1805de812915a17f16b11ab6a024a44070ae84e2d8b90c5971204b5b4 */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */


export interface MerchandisePurchaseChangeQuantity {
  quantity: number;
}
