/** File Hash: 5df88ae25c2d805d6cead7ce74a9460e1b7bb1d0d7e007a98c7edda5ce46531e */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */


export interface MerchandisePurchase {
  merchandiseProductId: number;
  quantity: number;
  usePoints: boolean | null;
}
