/** File Hash: b8e8dbf7163a3737138c9cf791cc03f1e40fc4269b37e000b20dfacf6dd68a4b */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */

import type { MerchandiseProductDetail } from "@/dtos/merchandise/merchandise-product-detail"

export interface MerchandisePurchaseDetail {
  id: number;
  usePoints: boolean | null;
  price: number;
  points: number;
  quantity: number;
  merchandiseProduct: MerchandiseProductDetail;
}
