/** File Hash: 6687c68c2e8285852a4ef0982234a45d7f6e78fabd8d200704c63f68ab966374 */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */


export interface MerchandiseProductCreate {
  name: string;
  description: string;
  price: number;
  points: number;
  stock: number;
  itemsPerCustomer: number;
  imageId: number;
}
