/** File Hash: 61aa68866ee7ab537d8967e44f0c023d430d051d97033fbc09844d23c6c4e511 */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */


export interface MerchandiseProductDetail {
  id: number;
  name: string;
  description: string;
  price: number;
  points: number;
  stock: number;
  itemsPerCustomer: number;
  imageName: string;
}
