/** File Hash: 1749ac469e9f41ed9c3e753f3da13cde5cfcf2829ae68d2baf9d4632b85f6b72 */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */

import type { IsoDateTimeString } from "@/dtos/iso-date-time-string"

export interface EventShowSearch {
  name?: string;
  startDate?: IsoDateTimeString;
  endDate?: IsoDateTimeString;
  duration?: number;
  minPrice?: number;
  maxPrice?: number;
  eventName?: string;
  locationName?: string;
  country?: string;
  city?: string;
  artistName?: string;
}
