/** File Hash: 862de76d52a616029e6ecd4366be6d26f75c4e6ddb900fbb07cb4eeed3a43788 */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */

import type { IsoDateTimeString } from "@/dtos/iso-date-time-string"

export interface EventShowCreate {
  name: string;
  startTime: IsoDateTimeString;
  endTime: IsoDateTimeString;
  price: number;
  eventId: number;
  locationId: number;
  artistId: number;
  seatingPlanId: number;
}
