/** File Hash: fbe177b835fab6330cb0c5d37f02bd63aa687d8d320a4ad79f3a9db5c9b77f75 */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */

import type { IsoDateTimeString } from "@/dtos/iso-date-time-string"
import type { EventDetail } from "@/dtos/event/event-detail"
import type { LocationDetail } from "@/dtos/location/location-detail"
import type { ArtistDetail } from "@/dtos/artist/artist-detail"

export interface EventShowDetail {
  id: number;
  name: string;
  startTime: IsoDateTimeString;
  endTime: IsoDateTimeString;
  price: number;
  event: EventDetail;
  location: LocationDetail;
  artist: ArtistDetail;
}
