/** File Hash: 4adb949e647a1681351a9b86dfbd1f5d0cfd7daaf736cfae2cf6edad34539968 */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */

import type { UserPaymentInfo } from "@/dtos/user/user-payment-info"
import type { PaymentType } from "@/dtos/payment-type"

export interface OrderPaymentInfo {
  userPaymentInfoDto: UserPaymentInfo;
  paymentType?: PaymentType;
  ticketIds: number[];
  merchandiseIds: number[];
}
