/** File Hash: e0601c3de0e8f420fa3e273d966598331d88dbdd869f40d0597609a90328e146 */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */

import type { TicketDetail } from "@/dtos/ticket/ticket-detail"
import type { MerchandisePurchaseDetail } from "@/dtos/merchandise/merchandise-purchase-detail"

export interface OrderDetail {
  id: number;
  orderNumber: string;
  deliveryAddress: string;
  tickets: TicketDetail[];
  merchandisePurchases: MerchandisePurchaseDetail[];
}
