/** File Hash: e2f8a4554d6f9cc01ca1dc331d5b4c7e0d1c1c994388829e9250acc5d514dc26 */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */

import type { EventType } from "@/dtos/event-type"

export interface EventCreate {
  title: string;
  type: EventType;
  description: string;
}
