/** File Hash: 2f00a17e86a31c166f7f288d1c6562be030d03784244753e83192f6cd6e3c981 */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */

import type { EventType } from "@/dtos/event-type"

export interface EventTopTen {
  type?: EventType;
}
