/** File Hash: ce9a0f3e037144b786b94ad1575df02a769dd394d59c4242440b57f5fcbec7c8 */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */

import type { EventType } from "@/dtos/event-type"

export interface EventSearch {
  title?: string;
  type?: EventType;
  duration?: number;
  description?: string;
}
