/** File Hash: 2f663a3badc38b6b40b2ffb314e6440f54461b1f56f8dc95c6e827d807e2b0ed */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */


export type EventType = "MOVIE" | "THEATRE" | "OPERA" | "CONCERT" | "COMEDY" | "SPORTS";
