/** File Hash: 00ce71dfee36752f3175299be172fa0356c47efe3696c329a6ab01b5fbec54bb */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */

import type { UserDetail } from "@/dtos/user/user-detail"

export interface ImageMedia {
  id: number;
  addedBy: UserDetail;
  name: string;
}
