/** File Hash: 421d9a21d3e8fc0567205bfbeed1aa08c3ae6138473f4fa69f4ec20d5559b598 */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */


export type MerchandiseSortOption = "NAME" | "PRICE_ASCENDING" | "PRICE_DESCENDING" | "POINTS_ASCENDING" | "POINTS_DESCENDING";
