/** File Hash: 9499ec6fd60984ce33324f867326b1301a698f69cf59170720cc0af8ee710318 */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */


export interface Page {
  pageIndex: number;
  pageSize: number;
}
