/** File Hash: 708c1d00180c214ce72f80f484006c249d045446664914b9c8781f33c5b1371f */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */


export interface Pagination<T> {
  elements: T[];
  total: number;
}
