/** File Hash: d61bf2ffa1c6a2fa4b855dbf3d7e14bf690ae8ca09764c6c3c66647231529c13 */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */


export type PaymentType = "VISA" | "DEBITCARD" | "PAYPAL";
