/** File Hash: d8e94689b1ac0f24210531c22b670413321b9ecb0d64e9df11b84b965896459f */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */


export interface Customer {
  name: string;
  lastName: string;
  address: string;
}
