/** File Hash: c32f99841978154908513be8483b167e654eb390690f4d57d03569ce3ef719fc */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */


export interface InvoiceItem {
  id: number;
  name: string;
  price: number;
  points: number;
  usePoints: boolean | null;
  quantity: number;
  VAT: number;
}
