/** File Hash: 9ef137568229c93b40d27558f4e2682e73b61f44eee03427bd02f7b327fe7f65 */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */


export interface ArtistDetail {
  id: number;
  firstName: string;
  lastName: string;
  stageName: string;
}
