/** File Hash: aa666ec548539d29a4fc1de06ba03388c5123699c8c461144f65d50d0b61049f */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */


export interface ArtistSearch {
  firstName?: string;
  lastName?: string;
  stageName?: string;
}
