/** File Hash: 737b53b4b5701352a2f1eb94109bc9a8a5fc73a03db75b52cd60955d32fded11 */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */


export interface UserEdit {
  firstName: string;
  lastName: string;
  address: string;
}
