/** File Hash: 05a9832e105615769bd673fef6dd961ba174f04aed58baa6dbca5bb738a3c97a */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */


export interface UserEditPassword {
  password: string;
  newPassword: string;
}
