/** File Hash: c2b77107915abcddf9e645dc327292e6c326a5a7ec05d21cdebe1274f694941b */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */


export interface User {
  firstName: string;
  lastName: string;
  email: string;
  password: string;
}
