/** File Hash: 68608537ed069dae7b294c675b17e416de0108b3898ee847bf629e462ab59ffd */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */


export interface UserPaymentInfo {
  firstName: string;
  lastName: string;
  address: string;
}
