/** File Hash: b01b2537f85a956048906d1704ad991984d38c62328396b38a7d8545d88d730d */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */


export interface UserDetail {
  id: number;
  email: string;
  firstName: string;
  lastName: string;
  address: string;
  points: number;
  isAdmin: boolean | null;
  isLocked: boolean | null;
}
