/** File Hash: 4d62bc07a9d692626e63ea518bc76fe58ab3faa168974e9f537f020648397edc */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */


export interface PasswordResetChange {
  token: string;
  email: string;
  password: string;
}
