/** File Hash: 9381d4dee9a2551ad0d1e355625e51222c218e1a5d76edff0579962dadf064f2 */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */


export interface PasswordResetDetail {
  token: string;
  email: string;
}
