/** File Hash: c066d6d6dd3113c79ea85883163a5c7181e8670a93251ca28de00894baff80a2 */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */


export interface PasswordResetCreate {
  email: string;
}
