/** File Hash: ab7ede9b08134865c72ba885cbe4084a68f8d67a6f55a9b4e5c5c491349a964e */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */

import type { PlaceType } from "@/dtos/place-type"
import type { TicketState } from "@/dtos/ticket-state"
import type { EventShowDetail } from "@/dtos/eventshow/event-show-detail"

export interface TicketDetail {
  id: number;
  seatingPlanSectorName: string;
  seatingPlanRowName: string;
  placeId: number;
  seatNumber: number;
  price: number;
  placeType: PlaceType;
  ticketState: TicketState;
  eventShow: EventShowDetail;
}
