/** File Hash: 5893c8d5acd0290c92b4cdd25ae9941f7fe060b09e76d802cfe1367fd4d62690 */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */

import type { TicketState } from "@/dtos/ticket-state"

export interface TicketSearch {
  state?: TicketState;
}
