/** File Hash: e65309a6f359a546d0a5d90151bbb582f80154331bfc910b704486fb538b2889 */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */


export interface TicketReservation {
  eventShowId: number;
  seatingPlanPlaceIds: number[];
}
