/** File Hash: 987a276a89f3fbbb27371cfa551a65c05d02e36a061870bd3bb16202c9dfc945 */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */


export interface TicketReservationsSearch {
  seatingPlanId: number;
  eventShowId: number;
}
