/** File Hash: 8afa1b9bda263bfbb9d3f79818173a078dd8ab3c1e0b1a22efaaeb7688839cf2 */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */

import type { TicketState } from "@/dtos/ticket-state"

export interface TicketMinimal {
  id: number;
  ticketNumber: string;
  price: number;
  placeId: number;
  ticketState: TicketState;
}
