/** File Hash: ece053d69530ff306fda80a36c804a9768c33ec77fba9bbbc7956ce906459146 */

/** Autogenerated Code - Do Not Touch */
/* eslint-disable */

import type { PlaceType } from "@/dtos/place-type"
import type { TicketState } from "@/dtos/ticket-state"

export interface TicketSeating {
  id: number;
  placeId: number;
  placeType: PlaceType;
  ticketState: TicketState;
}
